INSERT INTO DBSM.BPMN_MENU(ID_MENU, TITLE, TIPO_MENU, ID_SUP, TOOLTIP, ID_VERSAO, ICON, ORDEM, COD_OPERADOR, DT_ALTERACAO, HR_ALTERACAO, CONCORRENCIA, ENDERECO_FISICO)
	VALUES(1, 'NFS-e', 'M', NULL, 'Área relacionada a Nota Fiscal de Serviços Eletrônica.', NULL, NULL, 1, 121, SYSDATE, SYSDATE, 0, NULL)
GO
